### PR TITLE
improvements for the code

### PR DESCRIPTION
**Pull request by fagnersales**
Adding eslint to set up patterns/code style rules for the project

### CODE REVIEW

**Comment by MrLuisBR** [comment]
Can you explain more about it?

**Comment by fagnersales** [comment]
> Can you explain more about it?

Yep. Since you're working with an open source project, you might want to have some rules on your code. E.g. Use single/doublq quotes on strings, semicolons at the end of the code, etc.

**Comment by fagnersales** [comment]
I changed the pull request title because I'm working on improvement for all the project.

**Comment by MrLuisBR** [comment]
Thank you, I will put in future updates

**Comment by fagnersales** [comment]
I shouldn't send the pull request yet, since I didn't finish it, so keep it open and I'll ping you when finished

**Comment by MrLuisBR** [comment]
okok

**Comment by MrLuisBR** [comment]
Pode fechar?

**Comment by MrDrooxBR** [comment]
Closed, Malta now use Kotlin Programming Language and not needs ESLint but thanks for pull request

**Comment by MrLuisBR** [comment]
Se der merda e não entender nada eu volto pra js

**Comment by MrDrooxBR** [comment]
Só estudar direitinho, Kotlin não tem segredo nenhum

**Pull request closed without merging**
